[package]
name = "ragc-core"
version = "0.1.0"
authors = ["Om Dighe"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4"
heapless = "0.7.7"

[dev-dependencies]
ragc-ropes = { path = "../ragc-binaries" }

[features]
default = []
std = []
